# Generated by Django 6.1 on 2026-08-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True),
        ),
    ]
